# Generated by Django 5.2.8 on 2025-11-23 16:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('administration', '0002_membre'),
        ('visiteur', '0003_alter_cd_emprunteur_alter_dvd_emprunteur_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Emprunteur',
        ),
    ]
