# Generated by Django 5.2.8 on 2025-12-01 15:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administration', '0003_delete_emprunteur'),
    ]

    operations = [
        migrations.CreateModel(
            name='Media',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=200)),
                ('empruntable', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='JeuDePlateau',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=200)),
                ('createur', models.CharField(max_length=200)),
                ('empruntable', models.BooleanField(default=False)),
            ],
        ),
        migrations.RemoveField(
            model_name='membre',
            name='bloque',
        ),
        migrations.CreateModel(
            name='CD',
            fields=[
                ('media_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='administration.media')),
                ('artiste', models.CharField(max_length=200)),
            ],
            bases=('administration.media',),
        ),
        migrations.CreateModel(
            name='DVD',
            fields=[
                ('media_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='administration.media')),
                ('realisateur', models.CharField(max_length=200)),
            ],
            bases=('administration.media',),
        ),
        migrations.CreateModel(
            name='Livre',
            fields=[
                ('media_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='administration.media')),
                ('auteur', models.CharField(max_length=200)),
            ],
            bases=('administration.media',),
        ),
        migrations.CreateModel(
            name='Emprunt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_emprunt', models.DateTimeField(auto_now_add=True)),
                ('date_retour', models.DateTimeField(blank=True, null=True)),
                ('media', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='administration.media')),
                ('membre', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='administration.membre')),
            ],
        ),
    ]
