# Generated by Django 5.2.8 on 2025-11-28 17:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('visiteur', '0003_alter_cd_emprunteur_alter_dvd_emprunteur_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cd',
            name='emprunteur',
        ),
        migrations.RemoveField(
            model_name='dvd',
            name='emprunteur',
        ),
        migrations.DeleteModel(
            name='JeuDePlateau',
        ),
        migrations.RemoveField(
            model_name='livre',
            name='emprunteur',
        ),
        migrations.DeleteModel(
            name='CD',
        ),
        migrations.DeleteModel(
            name='DVD',
        ),
        migrations.DeleteModel(
            name='Livre',
        ),
    ]
